sudo: false
language: node_js
node_js:
  - "11"
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - yarn build
  - yarn coverage
after_success:
  - yarn coveralls
