sudo: false
language: node_js
node_js:
  - "11"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
script:
  - npm run build
  - npm run coverage
after_success:
  - npm run coveralls
